
//
// class DBAccessMode
//
// package org.eyedb.dbm
//
// Generated by eyedbodl at Thu Sep 10 15:18:44 2009
//

package org.eyedb.dbm;

import org.eyedb.utils.*;
import org.eyedb.syscls.*;

public class DBAccessMode extends org.eyedb.Enum {

  DBAccessMode(org.eyedb.Database db)
  {
    super(db);
  }

  DBAccessMode()
  {
    super();
  }

  public static final int NO_DBACCESS_MODE = 0;
  public static final int READ_DBACCESS_MODE = 16;
  public static final int WRITE_DBACCESS_MODE = 32;
  public static final int EXEC_DBACCESS_MODE = 64;
  public static final int READ_WRITE_DBACCESS_MODE = 48;
  public static final int READ_EXEC_DBACCESS_MODE = 80;
  public static final int READ_WRITE_EXEC_DBACCESS_MODE = 112;
  public static final int ADMIN_DBACCESS_MODE = 113;

  static org.eyedb.EnumClass make(org.eyedb.EnumClass DBAccessMode_class, org.eyedb.Schema m)
  {
    if (DBAccessMode_class == null)
      return new org.eyedb.EnumClass("database_access_mode");

    org.eyedb.EnumItem[] en = new org.eyedb.EnumItem[8];
    en[0] = new org.eyedb.EnumItem("NO_DBACCESS_MODE", 0, 0);
    en[1] = new org.eyedb.EnumItem("READ_DBACCESS_MODE", 16, 1);
    en[2] = new org.eyedb.EnumItem("WRITE_DBACCESS_MODE", 32, 2);
    en[3] = new org.eyedb.EnumItem("EXEC_DBACCESS_MODE", 64, 3);
    en[4] = new org.eyedb.EnumItem("READ_WRITE_DBACCESS_MODE", 48, 4);
    en[5] = new org.eyedb.EnumItem("READ_EXEC_DBACCESS_MODE", 80, 5);
    en[6] = new org.eyedb.EnumItem("READ_WRITE_EXEC_DBACCESS_MODE", 112, 6);
    en[7] = new org.eyedb.EnumItem("ADMIN_DBACCESS_MODE", 113, 7);

    DBAccessMode_class.setEnumItems(en);

    return DBAccessMode_class;
  }

  static void init_p()
  {
    idbclass = make(null, null);
  }

  static void init()
  {
    make((org.eyedb.EnumClass)idbclass, null);
  }
  public static org.eyedb.Class idbclass;
}

