
//
// class ExecutableLocalisation
//
// package org.eyedb.syscls
//
// Generated by eyedbodl at Thu Sep 10 15:18:45 2009
//

package org.eyedb.syscls;

import org.eyedb.utils.*;
import org.eyedb.syscls.*;

public class ExecutableLocalisation extends org.eyedb.Enum {

  ExecutableLocalisation(org.eyedb.Database db)
  {
    super(db);
  }

  ExecutableLocalisation()
  {
    super();
  }

  public static final int BACKEND = 1;
  public static final int FRONTEND = 2;
  public static final int STATIC_EXEC = 256;

  static org.eyedb.EnumClass make(org.eyedb.EnumClass ExecutableLocalisation_class, org.eyedb.Schema m)
  {
    if (ExecutableLocalisation_class == null)
      return new org.eyedb.EnumClass("executable_localisation");

    org.eyedb.EnumItem[] en = new org.eyedb.EnumItem[3];
    en[0] = new org.eyedb.EnumItem("BACKEND", 1, 0);
    en[1] = new org.eyedb.EnumItem("FRONTEND", 2, 1);
    en[2] = new org.eyedb.EnumItem("STATIC_EXEC", 256, 2);

    ExecutableLocalisation_class.setEnumItems(en);

    return ExecutableLocalisation_class;
  }

  static void init_p()
  {
    idbclass = make(null, null);
  }

  static void init()
  {
    make((org.eyedb.EnumClass)idbclass, null);
  }
  public static org.eyedb.Class idbclass;
}

